// <auto-generated />
namespace hLib.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class authorNationalityRequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(authorNationalityRequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201705021940419_authorNationalityRequired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
